# Generated by Django 5.2.4 on 2025-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarefa", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AF", "A Fazer"),
                            ("FE", "Feita"),
                            ("AN", "Em Andamento"),
                        ],
                        default="AF",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
